Give the ability to unset certificate and private keys data
jdauphant/ansible-role-ssl-certs pull request #27
Opened 2017-02-01 16:12 UTC by BboyKeen

Hi @jdauphant,

While using your role, I noticed it wasn't easy to unset the certificate and private key data for a specific host or environment.
My use case was to define certificate and private data for all environments except for my development environment where I want to use self-signed certificate.

With this PR, we are now able to generate self signed certificate by unsetting the vars this way
```
ssl_certs_local_privkey_data: ''
ssl_certs_local_cert_data: ''
```

If you have any idea to achieve this in a better way, please let me know.

2017-02-01 18:52 UTC, jdauphant commented
Hello @BboyKeen ,
Thanks for PR, good point !
I will prefer that we add `ssl_certs_local_privkey_data: ""` and `ssl_certs_local_cert_data: ""` in defaults/main.yml to improve self-documentation and keep simple comparisons inside the role.

2017-02-01 19:07 UTC, BboyKeen commented
That's a good idea.
I will add it tomorrow.

2017-02-03 13:17 UTC, BboyKeen commented
The modification has been done. We're good ?

2017-02-03 13:52 UTC, jdauphant requested changes

2017-02-03 13:52 UTC, jdauphant commented on tasks/main.yml
> +      and ( ssl_certs_local_privkey_data|d('') == '' and ssl_certs_local_cert_data|d('') == '' )
`|d('')` isn't needed

2017-02-03 13:52 UTC, jdauphant commented on tasks/main.yml
> +          and ssl_certs_local_cert_data is defined
`ssl_certs_local_privkey_data is defined and ssl_certs_local_cert_data is defined` can be removed

2017-02-03 13:52 UTC, jdauphant commented
@BboyKeen I have made some comments :)

2017-02-03 14:01 UTC, BboyKeen commented on tasks/main.yml
> +      and ( ssl_certs_local_privkey_data|d('') == '' and ssl_certs_local_cert_data|d('') == '' )
You're right. I didn't pay attention to that.

2017-02-03 14:06 UTC, BboyKeen commented
@jdauphant I've taken into account your comments.

2017-02-03 14:07 UTC, jdauphant approved these changes

2017-02-03 14:07 UTC, merged

2017-02-03 14:08 UTC, jdauphant commented
@BboyKeen Perfect, thanks :)